### ISSUE TITLE
Could not connect to Google Drive at this time

### ISSUE THREAD

**Issue by beausoleilmo** [CenterForOpenScience/osf.io#10957]
I've been trying to connect Google Drive for 2 days an it won't connect. 

I'm wondering if there is something I need to change on Google Drive's side to be able to use it on OSF.

I see that I'm supposed to see the folders like in the tutorial, but I just get the 'Could not connect to Google Drive at this time' 

https://help.osf.io/article/213-connect-google-drive-to-a-project 

Any thoughts on this?

**Comment by mfraezz** [comment]
Hi @beausoleilmo,

We've been in communication with Google recently about re-verification of our Google Drive OAuth application, which I suspect is what's causing this issue for you. We should have this resolved within the next two weeks. Thank you for your patience, and apologies for the trouble.

**Comment by beausoleilmo** [comment]
Thanks for the update!

**Comment by mfraezz** [comment]
@beausoleilmo, I believe this should be resolved for you now, as we've received affirmation for our app re-verification. Please confirm.

**Comment by bryan-harter** [comment]
I don't know if this is a related issue, but when I try to connect with my google drive account, my drive blocks OSF automatically:

![Image](https://github.com/user-attachments/assets/32ae5b48-e22f-41f6-9b5c-91bfba9d82bc)

**Comment by beausoleilmo** [comment]
@bryan-harter Don't know how you got that message, but this is what I was suspecting. Also, I still get the '`Could not connect to Google Drive at this time. Please try again later.`' . So I guess this is related.

**Comment by mfraezz** [comment]
@bryan-harter, that was due to a scope misconfiguration since app re-verification, and should no longer generate that error message. However, it appears that our GDrive is more limited in functionality since that re-verification process was completed, and in most circumstances can only manage files created through OSF, not existing ones on Drive. We've identified two potential paths to resolving that, but don't have an estimated completion date yet.

@beausoleilmo, if you're still receiving that message, could you write in to our Support Team at support@osf.io ? They should be able to help resolve it.

**Comment by bryan-harter** [comment]
I do see that it is working now, thanks! 

And yes I also saw that I could only work with files that were uploaded via OSF. I couldn't tell if that was a feature or a bug. Good to know that it is a bug!
