### ISSUE TITLE
Chrome: PDF navigation buttons sit too far to the right

### ISSUE THREAD

**Issue by jlcohoon** [CenterForOpenScience/osf.io#1629]
For landscape and vertical PDFs with multiple pages, the triangular forward/back buttons are off center. They are too far to the right on both the left and right sides. This only seems to occur in Chrome. 

![screen shot 2015-01-28 at 1 26 16 pm](https://cloud.githubusercontent.com/assets/4965832/5944153/c485a202-a6f2-11e4-9bc1-2c1790e355c2.png)

**Comment by brianjgeiger** [comment]
@jlcohoon is this fixed with the recent update?

**Comment by JeffSpies** [comment]
@icereval may have some info on this as well.

**Comment by jlcohoon** [comment]
Still sitting off to the right. I actually noticed this on staging during the testing, but it was the same on production so I listed the bug here. It's small, but still present after the latest release

**Comment by icereval** [comment]
At some point we'll need to implement the full featured pdf.js viewer which should correct some of these oddities in our custom viewer implementation.

Ex:
https://mozilla.github.io/pdf.js/web/viewer.html

**Comment by icereval** [comment]
For now @mfraezz can you see if you can correct this positioning behavior, thanks!

**Comment by mfraezz** [comment]
Planning on implementing http://viewerjs.org/ as a solution to this and as a catch-all solution to open-document formats (for which we currently have no support). This is low-priority compared to a Box addon for the osf, but I will get to it

**Comment by lbanner** [comment]
Thanks and agree @mfraezz

**Comment by lbanner** [comment]
@jlcohoon -- Is this not covered/overcome with the new PDF viewer in OSF, yes?

**Comment by jlcohoon** [comment]
It is!

**Comment by lbanner** [comment]
Cool - Thanks!
