### ISSUE TITLE
[staging & production] [feature request] Clicking on a component file in file tree eliminates parent project folders from tree

### ISSUE THREAD

**Issue by caileyfitz** [CenterForOpenScience/osf.io#2538]
Reported by @nicipfeiffer on the 0.32 Trello board: 

## Steps
1. Go to a project that has at least one component
2. Go to the files tab for the parent project
3. Click to View a file 
4. Click on a component file in the file tree
5. Look at the file tree, notice that the parent project files and folder are no longer visible

## Expected
From a user experience stand point: I would expect that if I was in the parent project looking at a file, then decided to look at a component file, I should be able to go back and forth between parent project files and component files in the file tree

## Actual
Once the user clicks to render a component file the parent project files are no longer in the tree and thus the user has to click out of the page to return to the parent project then> files tab, then> click to render a file.  A LOT of steps!

From @samanehsan: 
> Yes, when you go to the files tab of a project you see all of the project & component files. But when you go to the files tab of one of those components you just see component files. The parent project files are no longer included.

**Comment by nanchen47** [comment]
This is solved by @samanehsan 's file page tree view.

**Comment by samanehsan** [comment]
@nanchen47, the issue that @caileyfitz pointed out is still the current behavior of our file grids and is not solved by the file page tree view. When a user is viewing a project file and clicks to view a file in one of the components, they are still taken to the component project and shown only the component's files in the grid.
