### ISSUE TITLE
old file version is not rendering the correct version

### ISSUE THREAD

**Issue by jlcohoon** [CenterForOpenScience/osf.io#2609]
<h4>Steps</h4>
1. Visit this file: https://osf.io/ezrsc/?version=3
2. Click on version two to render it. 
3. Download version two.

<h4>Outcome</h4>
1. Version 2 incorrectly renders the same file as version 1.
2. Version 2 downloads the correct file; it does not correspond to what is rendered, however.

<h4>Expected Outcome</h4>
1. Versions should display and download the same file versions. 
2. Renderings of versions should accurately display the state of the file at that time.

Note that I haven't been able to reproduce this error yet—I can only find this occuring with that particular file.

**Comment by sloria** [comment]
@jlcohoon Thanks for reporting. This should now be fixed.

**Comment by mckidwell** [comment]
@sloria @lbanner I am still experiencing this issue with a PDF in a private component. I can add you to the component if you want to take a look.

The initial file was a PDF too - this may only be affecting PDFs.

**Comment by lbanner** [comment]
Yeah ... please do @mckidwell

**Comment by mckidwell** [comment]
@lbanner added you to the component (https://osf.io/8kt4b/)

File in question is "Article Codebook" -- it renders the same (most recent) version for both Version 1 and 2, but downloads the correct file.

**Comment by lbanner** [comment]
OK - yes - thanks @mckidwell - 
If specific to this, maybe a migration solution @sloria ?
