### ISSUE TITLE
DAZ: Google Drive Add-on Error

### ISSUE THREAD

**Issue by wisherp** [CenterForOpenScience/osf.io#2838]
STEPS
1. Go to a project
2. Enable Google Drive
3. Go to the Files tab
4. Click on the Google Drive folder for the project to highlight it
5. Ensure that you see the Download as Zip button in the toolbar
6. Click the Download as Zip button

EXPECTED
The folder would be downloaded as .zip and could be opened to view its contents.

ACTUAL
The file downloads but gives an error when trying to open it. 

![screen shot 2015-05-26 at 3 35 48 pm](https://cloud.githubusercontent.com/assets/10926926/7821528/4ddba89a-03bd-11e5-9451-eebb4e91c485.png)

Link to the trello card: https://trello.com/c/NbdgsXL5/218-daz-google-drive-add-on

**Comment by GaryKriebel** [comment]
@chrisseto and/or @lyndsysimon .... is this related to what you were working on yesterday?  Looks like there are special characters in the filenames.

**Comment by chrisseto** [comment]
@wisherp Please make the project public or add me as a contributor and provider a link to it.
@GaryKriebel This may be related to an issue regarding googledocs that we ran into earlier today.

**Comment by wisherp** [comment]
@chrisseto I added you as a contributor. Here's the link : https://osf.io/ts7x6/

**Comment by chrisseto** [comment]
@wisherp Thank you very much
This is an issue with how we deal with googledocs which needs to be discussed.

**Comment by chrisseto** [comment]
@wisherp This issue should have been fixed around 0.39

**Comment by wisherp** [comment]
@chrisseto still seeing this on production so not sure if it was fixed then, @GaryKriebel 
![screen shot 2015-06-16 at 10 24 39 am](https://cloud.githubusercontent.com/assets/10926926/8185522/eb9e46cc-1412-11e5-9ebd-451a9c70b9a5.png)

**Comment by chrisseto** [comment]
@wisherp I'm not seeing this on the project the you previously linked to, could you add me to the new one?

**Comment by wisherp** [comment]
@chrisseto yes, here's the link: https://osf.io/5crta/

**Comment by chrisseto** [comment]
@wisherp Could you link the root folder to "longerfoldername" I think the creatively named docx files might be the cause of this.

**Comment by wisherp** [comment]
@chrisseto sorry, just wanna make sure, what are you referring to when you say "root folder"?

**Comment by chrisseto** [comment]
@wisherp The folder that is linked to the project.

**Comment by wisherp** [comment]
@chrisseto cool. Done.

**Comment by chrisseto** [comment]
@wisherp Looks like that is the issue, the original issue which had to do with google docs is fixed however.

**Comment by wisherp** [comment]
@chrisseto interesting. I just deleted all of the docx files and tried to download the folder but am still getting the same error...

**Comment by chrisseto** [comment]
Whoops, jumped to the wrong conclusion. 
You have a google form in one of your folders and it looks like google doesn't expose an easy way to download them. From the google drive interface the only download offered is the responses as csv.
@lbanner @GaryKriebel Thoughts on how to handle that?

**Comment by chrisseto** [comment]
https://stackoverflow.com/questions/18508281/how-to-download-google-drive-form-programmatically

**Comment by GaryKriebel** [comment]
@chrisseto -- are we able to exclude the download button for Google Forms as well as stripping it from the zip?

**Comment by chrisseto** [comment]
Going with @brianjgeiger's suggestion we are going to exclude google forms from waterbutler metadata listings.

**Comment by chrisseto** [comment]
This is fixed as of https://github.com/CenterForOpenScience/waterbutler/releases/tag/0.6.3
@wisherp can you confirm?

**Comment by wisherp** [comment]
@chrisseto Still getting the same error while trying to download google drive folders as zip...

**Comment by wisherp** [comment]
@chrisseto This is working now when the folders don't have .gslides files!

**Comment by wisherp** [comment]
DAZ for Google Drive seems to be working fine now so closing this now.
