### ISSUE TITLE
[production] File upload stops part-way through and does not resume

### ISSUE THREAD

**Issue by caileyfitz** [CenterForOpenScience/osf.io#3019]
# Steps
1. Go to a newly created project on production (or if you don't have one, create one)
2. Go to the files tab
3. Drag and drop 10+ files of varying types to upload them into OSF Storage
4. Wait for uploads
5. If one upload pauses, press the **x** button to cancel that upload
6. Wait for other files to upload

# Expected 
I expect that all files would upload within a reasonable amount of time. For step 6, I expect after canceling one upload, all remaining files would continue to upload

# Actual
On three different occasions, upon trying to upload a group of files, upload stopped after uploading only one or a couple of files. I have been waiting ten minutes for tulips.jpg to upload: 
![udd](https://trello-attachments.s3.amazonaws.com/556763cb1b65c5c5de77322f/600x269/66238f4eb6936406a9e7a4398220ab23/Screen_Shot_2015-05-28_at_2.51.18_PM.png)

After pressing the **x** to cancel that one upload, none of the other files continue with upload. The page just sits with no apparent processes running, although trying to leave the page gives a pop-up modal saying that files are being uploaded, even though they are not. 
![ias](https://trello-attachments.s3.amazonaws.com/556763cb1b65c5c5de77322f/600x186/e5695f8c9c1f2923352e45ac5f5de53b/Screen_Shot_2015-05-28_at_2.58.00_PM.png)

**Comment by lbanner** [comment]
@chrisseto ..... WaterButler? Thanks.

**Comment by chrisseto** [comment]
My first guess is Treebeard/Fangorn, @caneruguz?

**Comment by caneruguz** [comment]
This is very hard to tell what exactly is going on, I need to try to replicate this to understand but I don't know if this is strictly fangorn. I'll find out though. 

@lbanner can you assign me?

**Comment by lbanner** [comment]
Done!

**Comment by caileyfitz** [comment]
Just as an update, this occurred for me again today, so I know that it is still an issue.

**Comment by lbanner** [comment]
@caneruguz -- Had time to look into this one? TY

**Comment by caneruguz** [comment]
I'm working on upload canceling but I can't replicate this case again. @caileyfitz any further details would help but it looks tought to pin down.

**Comment by caileyfitz** [comment]
@caneruguz Now that we have parallel file uploads, I am no longer seeing this issue, so I am going to close this.

**Comment by caneruguz** [comment]
Okay I also sent a fix to improve cancel upload consistency so hopefully this will take care of things.

**Comment by caileyfitz** [comment]
@caneruguz Great, thanks!
