### ISSUE TITLE
[Production & Staging] Inconsistent end-of-log behavior

### ISSUE THREAD

**Issue by NatashaRichter** [CenterForOpenScience/osf.io#3230]
## Steps

1. Log in to osf.io.
2. Navigate to one of your projects which has a lot of activity in the log (at least 8 or 9 pages) or go to the "Center for Open Science" project, which has many pages.
3. Click through the different pages of the log at a regular pace the first time through, faster the second time through, and even faster a third time through.
4. Notice the last page of the log.

## Expected behavior

I expect that the last page shown will be my final activity.

## Actual behavior

Sometimes, the last page of the log reads, "No logs to show. Click the watch icon () icon on a project's page to get activity updates here." If I have accidentally clicked through the log too fast, then I have to click the left arrow button of the log the same number of times to return to the actual last page of the log (as opposed to the "No logs to show" page), which is sometimes a lot of clicks. I think that the "No logs to show" page should not be counted as a "page" and therefore the user would not need to click the left arrow button so many times to return to the final page of the log.

## Screenshots

![watchicon](https://cloud.githubusercontent.com/assets/7093086/8256366/acfcfbf2-1674-11e5-87ee-f2e8e17dbab4.png)

**Comment by chennan47** [comment]
This will be fixed by https://github.com/CenterForOpenScience/osf.io/pull/3224

**Comment by sloria** [comment]
Migration was run. @NatashaRichter Can you confirm that this was fixed?

**Comment by NatashaRichter** [comment]
@sloria Still seeing this end-of-log behavior on Production (on more than one project):

![end of log](https://cloud.githubusercontent.com/assets/7093086/8330833/3f2a2fa0-1a52-11e5-8925-643106000644.png)

**Comment by chennan47** [comment]
This is the box log error which will be fixed by https://github.com/CenterForOpenScience/osf.io/pull/3265. It's not caused by log migration.

**Comment by sloria** [comment]
@NatashaRichter The logs should now be fixed. Can you please verify?

**Comment by NatashaRichter** [comment]
@sloria @nanchen47 Still seeing "No logs to show" at end of logs upon clicking rapidly to the end (and still have to click back for awhile to return to the actual logs). Just reproduced on this project:

https://osf.io/vnmyr/

Added Nan as an admin to the project.

**Comment by sloria** [comment]
@NatashaRichter Can you add me as a contributor as well?

**Comment by chennan47** [comment]
Sry I mean I can't repo the problem. It works fine for me.

**Comment by NatashaRichter** [comment]
@chennan47 Yes, Nan, I talked to Steve (will show you, too); it's now a different log problem (related) that I am seeing and will create a new issue for. Let's talk via flowdock to meet.
